n = input('Digite algo: ')
print(n.isalnum())
print(n.isalpha())
print(n.isdecimal())
print(n.isdigit())
print(n.isidentifier())
print(n.islower())
print(n.isnumeric())
print(n.isprintable())
print(n.isspace())
print(n.istitle())
print(n.isupper(), "\n")

cf = str(input("Você deseja ver o codigo fonte?"))
if cf == "sim" or "s" or "Sim":
    f = open('Desafio4', 'r')
    print(f.read())
