nome=input('qual é o seu nome ?')
idade=input ('qual a sua idade ?')
peso=input('qual o seu peso ?')
print('Olá',nome)
print('sua idade é',idade , 'anos')
print ('e seu peso é',peso)
resposta 1 = input('você acha que para a sua idade voce esta no peso ideal ?')
